### PR TITLE
Bump SocketRocket version to 0.4.x

### PR DESCRIPTION
**Pull request by bithavoc**
Bumping SocketRocket to 0.4 stable.

**question:** current spec version is `0.2.1`, should I send another PR to bump the cocoapods file to `0.2.2` or `0.3.0`?

### CODE REVIEW

**Comment by guilleiguaran** [comment]
:+1:

**Comment by Ecarrion** [comment]
:+1:

**Comment by kmilitagaitan** [comment]
:+1:

**Comment by joshdholtz** [comment]
@bithavoc Thank you! :grin: :raised_hands: :whale:

**Comment by joshdholtz** [comment]
Pushing a new version to cocoapods here shortly

**Comment by bithavoc** [comment]
Thank you @joshdholtz

**Comment by joshdholtz** [comment]
New release should be up now! https://cocoapods.org/pods/Phoenix-ObjC

**Pull request merged**
